import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import SocketProvider from "./SocketProvider";
import { AuthProvider } from "../context/AuthContext";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // Don't forget this!
import { SocketProvider } from "@/context/SocketContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "رایا دیلماج",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        /></Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <AuthProvider>
          <SocketProvider>
            {children}
            <ToastContainer
              position="bottom-center"
              autoClose={4000}
              hideProgressBar={false}
              newestOnTop
              theme="dark"
              closeOnClick
              rtl // ✅ RTL support for Persian
              pauseOnFocusLoss
              draggable
              pauseOnHover
              toastClassName="CustomToast"
              bodyClassName="CustomBody"
              progressClassName="CustomProgress"
            />

          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
